apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: local-secret-store
  namespace: default
spec:
  type: secretstores.local.localsecretstore
  metadata:
  - name: secretsFile
    value: ./components/secrets.json